### PR TITLE
touch: Use full 12-bit X and Y values

### PR DESCRIPTION
**Pull request by mcudev**
I was getting truncated touch coordinate values on my 240x320 screen.
This changes to use the full 12-bit X and Y values (reference the touch panel controller manual) and still leaves plenty of event type bits.

### CODE REVIEW

**Comment by mcudev** [comment]
if you stack this on top of https://github.com/trezor/trezor-core/pull/72, then no further coordinate mapping is strictly necessary. stuff just works.

**Comment by mcudev** [comment]
about going into bootloader mode by pressing during power on: the user has to do something more than just hold down their finger and plug-in/reset/power-up the device. the touch panel controller chip only sends back useless reports until a significant (capacitance changing) event occurs. even pressing and moving without lifting the finger will not generate such an event unless done quickly/far enough (verified in debugger).

**Comment by mcudev** [comment]
@jpochyla Do you happen to know if the touch panel controller interrupt or reset lines are connected in the hardware design? Or, can you tell me which lines to the touch panel controller are connected to the MCU (obviously, I know I2C clock and data and 3v3 and GND are)?

**Comment by prusnak** [comment]
EINT is connected to PC4, REST is connected to PC5

**Comment by prusnak** [comment]
Btw, have you received the boards I've sent you already?

**Comment by mcudev** [comment]
@prusnak I did, but there were problems, check your email (I thought you were just ignoring me, lol).

**Comment by prusnak** [comment]
Emails sent.

**Comment by mcudev** [comment]
thanks!

**Comment by prusnak** [comment]
Thanks!

**Pull request merged**
