### PR TITLE
Wanchain

### PR DESCRIPTION
**Pull request by tyrion70**
Added support for Wanchain. In order to display the name Wan in the display I made a change to layout.py and networks.py since the chain_id of wanchain is currently set to 1 as well. If and when the chain_id is set to another id it can be reverted. Hope this is an acceptable solution for now.

### CODE REVIEW

**Comment by jhoenicke** [comment]
I think we should check that tx_type is None or 1.  Just as a safety precaution that we don't sign a transaction we don't understand. 

Is there a reason to use "bytes" for tx_types instead of, e.g., uint32?  The latter would be easier, but may be an issue if they use tx_types with more than 32 bits some day.

**Comment by tyrion70** [comment]
I checked about the tx_type, its currently either 0x01 or 0x06 so I can change it to an uint32 safely. I agree that adding a precaution to sign only those is prudent, I'll add that to the check function in sign_tx.py. 

Regarding the tx_type change to uint, I can do that, but I'd need to change trezor-common then as well again. @prusnak you got any preferences here? I would personally prefer keeping it bytes now since it would have been easier only if I had done it from the start ;) But I'm fine with changing it in all repos.

**Comment by prusnak** [comment]
Please change to uint32 if possible.

**Comment by tyrion70** [comment]
Tx_type was changed to uint in all three repo's. latest trezor-common was used to generate again. Check was also added to only allow tx_type 1, 6 and None.
@jhoenicke @prusnak please let me know if i need to add anything more. Thanks!

**Comment by prusnak** [comment]
Can you please rebase on top of master? There were some fixes and your changes are in conflict with them.

**Comment by tyrion70** [comment]
@prusnak I just rebased with master as per your request.

**Comment by prusnak** [comment]
Thanks!

**Pull request merged**
