### PR TITLE
Run emulator in docker

### PR DESCRIPTION
**Pull request by vladimirvolek**
resolves: https://github.com/trezor/trezor-core/issues/415

### CODE REVIEW

**Comment by tsusanka** [comment]
Agreed, we'll look into this after bridge is added.

**Comment by vladimirvolek** [comment]
Bridge in docker: https://github.com/trezor/trezord-go/pull/125

**Comment by vladimirvolek** [comment]
related to https://github.com/trezor/trezor-wallet/pull/311

**Comment by tsusanka** [comment]
Merged via 6ea25bd38657c957b7f90b53a51558bf224b0adc

**Pull request closed without merging**
