### PR TITLE
issue 12: startup related changes

### PR DESCRIPTION
**Pull request by mcudev**
@prusnak Here's some work towards https://github.com/trezor/trezor-core/issues/12. It's ok, but, I'm not sure I totally like it. I have some other versions that don't depend on the HAL and are way smaller and incorporate a lot of other review notes that I haven't mentioned yet. Maybe take a glance and let me know your reaction / first opinion, please.

I think the reason why I removed the exception handlers in this commit (from a few weeks ago IIRC) was because the code they run is not reliable during those exceptions anyways.

### CODE REVIEW

**Comment by prusnak** [comment]
Generally, I really like the direction this is going.

We are in the process of finalizing boardloader (by Monday), so you are more than welcome to share other stuff that needs review.

Just a really small nitpick, can we keep `FLASH`/`CCMRAM`/`RAM` uppercase and `rx`/`wal` lowercase to stay consistent with micropython?

Also, now that we dropped `__fatal_error` from all handlers, can we at least indicate we are in the `default_handler` (simple pattern using display PWM comes to mind). What do you think>

**Comment by prusnak** [comment]
Also `NMI_Handler`, `SVC_Handler` and `DebugMon_Handler` were empty, but now they will result in infinite loop. Is that intended?

**Comment by mcudev** [comment]
> Just a really small nitpick, can we keep FLASH/CCMRAM/RAM uppercase and rx/wal lowercase to stay consistent with micropython?

Done, just rebased and force pushed.

> Also, now that we dropped __fatal_error from all handlers, can we at least indicate we are in the default_handler (simple pattern using display PWM LED comes to mind).

Maybe in things after the boardloader. But early in the boardloader, no. IIRC, I came to this conclusion while playing around glitching my clock (while testing some stuff I had done around the clock security system). On my dev board, it was really easy to trigger the CCS by touching a specific pin (I guess my finger had enough capacitance to throw off the HSE).

> Also NMI_Handler, SVC_Handler and DebugMon_Handler were empty, but now they will result in infinite loop. Is that intended?

Yes, I figured that was one safe way to fail and is easy to review :) Definitely the case for NMI because that's where the CSS fails to.

> We are in the process of finalizing boardloader (by Monday), so you are more than welcome to share other stuff that needs review.

OK, I'll need to dig out my notes and other code tonight and refresh my thinking (it's been like a month). Generally, things I had on my mind were:
 * Setup clocks (clock security system too) and RNG before wiping memory?
 * Any other peripheral local memories that should/could be cleared? e.g.- display, usb, touch sensor, fsmc, sdio?
 * port over mature `memory_protect` and RNG using code from TREZORv1
 * glitching protection and checks (I've read some of the public literature about v1 attacks)
 * there's an awful lot that goes into linking the boardloader right now that is unnecessary; could definitely be cleaned up; want the boardloader very small and well understood because that's what gets write protected.
 * and more, but I forget right now...

**Comment by prusnak** [comment]
> Done, just rebased and force pushed.

Thank you, just merged!

> On my dev board, it was really easy to trigger the CSS by touching a specific pin (I guess my finger had enough capacitance to throw off the HSE).

That's how I was checking whether CSS works on T1  :-)

> OK, I'll need to dig out my notes and other code

Please do, would love to see these!

**Pull request merged**
