### PR TITLE
added CoinInfo for Actinium (ACM)

### PR DESCRIPTION
**Pull request by brakmic**
Expanded *COINS* array in coininfo.py.

I've already checked the protos in *trezor-common* but couldn't find anything that should be adapted to Actinium. However, there is a high probability that I have missed some important parts, so please, correct me if I am wrong.

I am currently reading the docs on API, Testing, and Emulation in *trezor-core*. 

Regards,

### CODE REVIEW

**Comment by matejcik** [comment]
the file you edited is autogenerated.

you will need to add the appropriate data to trezor-common/defs, update reference in trezor-core and regenerate this file with `make templates`

**Comment by matejcik** [comment]
seeing that ACM is already merged in trezor-common, all left to do is the steps outlined above

**Comment by brakmic** [comment]
Many thanks for the explanation! 👍

**Comment by matejcik** [comment]
Submodule references in Git point to a specific commit by design. What your `git clone --recursive` does is fetch _that particular commit_. It's not supposed to get the latest version; on the contrary, _you're_ supposed to update the reference so that it points to a commit with your defs in it. (usually to the most up-to-date version, through e.g. going to the `vendor/trezor-common` subdir and `git checkout master; git pull`)

**Comment by brakmic** [comment]
Many thanks. Already changing it!

**Pull request closed without merging**
