### PR TITLE
Add Groestlcoin support

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**
Tests are not yet updated. Please review are these changes acceptable.

### CODE REVIEW

**Comment by prusnak** [comment]
Some tests are failing in Travis, see here:
https://travis-ci.org/trezor/trezor-core/jobs/398907671
Most probably you just forgot to add API changes to the tests.

Also please add Groestl512 tests similar to
https://github.com/trezor/trezor-core/blob/master/tests/test_trezor.crypto.hashlib.sha512.py

**Comment by yura-pakhuchiy** [comment]
@prusnak Thank you! I've fixed existing tests and  added some test vectors from groestl reference implementation: www.groestl.info/Groestl.zip

**Comment by yura-pakhuchiy** [comment]
I've added tests for Groestlcoin addresses and transaction signing to ensure that changes to other coins will not break GRS accidentally.

**Comment by prusnak** [comment]
Thanks! Looks great!

**Pull request merged**
