### PR TITLE
display_identify: re-identify for each code stage

### PR DESCRIPTION
**Pull request by mcudev**
https://github.com/trezor/trezor-core/pull/296#issuecomment-410465060

this just gets the display working for my dev kit and prototype boards. may need refactoring.

### CODE REVIEW

**Comment by prusnak** [comment]
I just pushed another approach into https://github.com/trezor/trezor-core/tree/display_id_refactor branch.

Both approaches have its (dis)advantages:

yours - smaller code, more error-prone to refactoring mistakes (programmer forgets to call display_identify)
mine - bigger code, less error-prone

Not sure which one to pick :-)

**Comment by mcudev** [comment]
we can go with yours. it keeps it all in one file.

**Comment by prusnak** [comment]
Ok, closing in favor of e3d18ecb474f542f88ece3bfacae6bfa5d3055e3

**Comment by mcudev** [comment]
cool, hey do you want to grab the small update to docs/hardware.md ?

**Comment by prusnak** [comment]
Docs update done on the following commit.

**Pull request closed without merging**
