### PR TITLE
docs: add reference hardware and dev kit info

### PR DESCRIPTION
**Pull request by mcudev**
This is a rough draft (not ready to be merged) to get the discussion going.
I'm trying to piece together what is needed from the code, and searching Google.
For example, there are some TODOs with questions.

Referencing https://github.com/trezor/trezor-core/issues/8

### CODE REVIEW

**Comment by prusnak** [comment]
Thanks!

**Comment by prusnak** [comment]
We are using LQFP100 variant of STM32F405, because we need FSMC controller to push 8-bit parallel into the display.

**Comment by mcudev** [comment]
Ah, I was wondering that when I saw it was not supported on the STM32F405RG in the datasheet. I was hoping it was a mistake.

**Comment by mcudev** [comment]
I was wondering if you tried SPI for the SD card and found it unacceptable? Using SPI instead makes it more accessible for hobbyist use and would allow the design to go back to the LQFP64.

**Comment by prusnak** [comment]
We used the reference design from pyboard and this used SDIO, but I think SPI should be also fine.

**Comment by mcudev** [comment]
The pyboard uses a STM32F405RGT6 though. How could it use SDIO without the FSMC memory controller? FWIW, breakout boards with a display, touch, and SPI microSD are easier to get.

**Comment by prusnak** [comment]
We use FSMC for display, SDIO for SD card.

**Comment by mcudev** [comment]
Doh, you're right, I mixed that up. The displays are commonly driven with SPI on the breakouts too. Any chance that SPI could be used for the display, or is that too slow?

**Comment by prusnak** [comment]
The display we picked does not have SPI, that's why we use FSMC. I think you could be fine with SPI as well. The change needed to support both should be really trivial in code.

**Comment by mcudev** [comment]
Interesting. Thanks for the help! I'll look into it.

**Comment by prusnak** [comment]
I would say: try getting a breakout board with SPI display and microSD and we'll update the code to work on both platforms (SPI+SPI and FSMC+SDIO) together. Should not be a big issue at all.

**Comment by mcudev** [comment]
Wow, cool, will do.

**Comment by mcudev** [comment]
I found some parts that may match closer to the existing code. I'll update you after I try them.

Which version of the pyboard reference design did you use (I'm guessing 1.0)? The differences are listed at the bottom of https://store.micropython.org/#/features.

It looks like the code is configured for an 8 MHz high-speed external crystal. That's a good common frequency on available parts -- are you sticking with that?

**Comment by prusnak** [comment]
Pyboard v1.1 was used as the reference. But we use 8MHz crystal.

**Pull request merged**
