### PR TITLE
Tezos integration

### PR DESCRIPTION
**Pull request by jurajselep**

### CODE REVIEW

**Comment by prusnak** [comment]
Please remove the `patch` file from the commit.

**Comment by prusnak** [comment]
Don't merge unless https://github.com/trezor/trezor-common/pull/139 is merged first

**Comment by prusnak** [comment]
Can you please rebase on top of master?

Also we started to use [black](https://pypi.org/project/black/) and [isort](https://pypi.org/project/isort/) for our python code in `src/` so please use this to avoid being rejected by Travis.

**Comment by Adman** [comment]
Rebased it, but `sign_tx` is not done yet. I will create a pull request to trezor-common with updated fields.

**Comment by prusnak** [comment]
Ack!

**Comment by Adman** [comment]
updated fields of trezor-common https://github.com/trezor/trezor-common/pull/170

**Comment by prusnak** [comment]
This is still work in progress - closing for now. Reopen once you are finished and want to have this reviewed. Thanks!

**Pull request closed without merging**
