### PR TITLE
display_identify: improve identification of ILI9341

### PR DESCRIPTION
**Pull request by mcudev**
I found another ID register in the datasheet for the ILI9341. 0xD3 is not mentioned in the ST7789V datasheet. That is why I only read the register if we don't already have a positive identification from the 0x04 register.

tested on prototype board + st7789v and with dev kit + ili9341.

### CODE REVIEW

**Comment by prusnak** [comment]
Nice! Thanks!

**Comment by prusnak** [comment]
Did small related refactor in bc5dba751a0a0078efd33fe1550222087823f0a6

**Comment by mcudev** [comment]
i like that refactor! thanks!

**Comment by prusnak** [comment]
And finally the runtime detection of connected display controller: 3022cd50c80975c1cc4a812e3d5e079cb9665eb7

Comments welcome!

**Comment by mcudev** [comment]
will review. do you have a manual or datasheet for GC9307 anywhere? couldn't find one.

**Comment by prusnak** [comment]
Sent via email

**Comment by mcudev** [comment]
review:
- [x] no more extra build flags and recompiling, yay!
- [x] all references to DISPLAY_ILI9341V, DISPLAY_ST7789V, DISPLAY_GC9307 are removed
- [ ] need to re-identify for each code stage to set DISPLAY_ID since it gets re-initialized every time to 0 (.bss section variable).
- [ ] may want to update hardware.md to: `Driver IC: ST7789V, GC9307, or ILI9341V (on-chip display data RAM of 240x320x18 bits)`

**Pull request merged**
